Update tblProducts set Brand=N'Yamaha' where [Name] like N'%Yamaha%'
Update tblProducts set Brand=N'Casio' where [Name] like N'%Casio%'
Update tblProducts set Brand=N'Roland' where [Name] like N'%Roland%'
Update tblProducts set Brand=N'Kawai' where [Name] like N'%Kawai%'
Update tblProducts set Brand=N'Valote' where [Name] like N'%Valote%'
Update tblProducts set Brand=N'Takamine' where [Name] like N'%Takamine%'
Update tblProducts set Brand=N'Fender' where [Name] like N'%Fender%'
Update tblProducts set Brand=N'Alesis' where [Name] like N'%Alesis%'
Update tblProducts set Brand=N'Aroma' where [Name] like N'%Aroma%'
Update tblProducts set Brand=N'Taylor' where [Name] like N'%Taylor%'
Update tblProducts set Brand=N'Cordoba' where [Name] like N'%Cordoba%'
Update tblProducts set Brand=N'Chard' where [Name] like N'%Chard%'
Update tblProducts set Brand=N'Takavood' where [Name] like N'%Takavood%'
Update tblProducts set Brand=N'Temeisheng' where [Name] like N'%Temeisheng%'
Update tblProducts set Brand=N'Bock' where [Name] like N'%Bock%'
Update tblProducts set Brand=N'Sqoe' where [Name] like N'%Sqoe%'
Update tblProducts set Brand=N'D Addario' where [NameUnsign] like N'%D Addario%'
Update tblProducts set Brand=N'Nissi' where [Name] like N'%Nissi%'
Update tblProducts set Brand=N'Savarez' where [Name] like N'%Savarez%'
Update tblProducts set Brand=N'Tokado' where [Name] like N'%Tokado%'
Update tblProducts set Brand=N'Tanglewood' where [Name] like N'%Tanglewood%'
Update tblProducts set Brand=N'Martin' where [Name] like N'%Martin%'
Update tblProducts set Brand=N'Marshall' where [Name] like N'%Marshall%'
Update tblProducts set Brand=N'Soundking' where [Name] like N'%Soundking%'
Update tblProducts set Brand=N'Tascam' where [Name] like N'%Tascam%'
Update tblProducts set Brand=N'Oniix' where [Name] like N'%Oniix%'
Update tblProducts set Brand=N'Kapok' where [Name] like N'%Kapok%'
Update tblProducts set Brand=N'Boss' where [Name] like N'%Boss%'
Update tblProducts set Brand=N'Hippo' where [Name] like N'%Hippo%'
Update tblProducts set Brand=N'Finlay' where [Name] like N'%Finlay%'
Update tblProducts set Brand=N'Lanikai' where [Name] like N'%Lanikai%'

Update tblProducts set Brand=N'Kriens' where [Name] like N'%Kriens%'
Update tblProducts set Brand=N'Alice' where [Name] like N'%Alice%'


Select * from tblProducts where Brand is null



  Update tblProducts set Brand=N'CleproX' where [Name] like N'%CleproX%'
Update tblProducts set Brand=N'Clepro' where [Name] like N'%Clepro%'
Update tblProducts set Brand=N'Fasa' where [Name] like N'%Fasa%'
Update tblProducts set Brand=N'Hiclean' where [Name] like N'%Hiclean%'
Update tblProducts set Brand=N'Anex' where [Name] like N'%Anex%'
Update tblProducts set Brand=N'Fiorientini' where [Name] like N'%Fiorientini%'
Update tblProducts set Brand=N'Typhoon' where [Name] like N'%Typhoon%'
Update tblProducts set Brand=N'Camry' where [Name] like N'%Camry%'
Update tblProducts set Brand=N'IPC' where [Name] like N'%IPC%'
Update tblProducts set Brand=N'Karcher' where [Name] like N'%Karcher%'
Update tblProducts set Brand=N'Panasonic' where [Name] like N'%Panasonic%'
Update tblProducts set Brand=N'Kenper' where [Name] like N'%Kenper%'
Update tblProducts set Brand=N'CleanMaid' where [Name] like N'%CleanMaid%'
Update tblProducts set Brand=N'Camry' where [Name] like N'%Camry%'
Update tblProducts set Brand=N'Hiclean' where [Name] like N'%Hiclean%'
Update tblProducts set Brand=N'Eureka' where [Name] like N'%Eureka%'

Update tblProducts set Brand=N'D Delfin' where [NameUnsign] like N'%D Delfin%'
Update tblProducts set Brand=N'Lavor' where [Name] like N'%Lavor%'
Update tblProducts set Brand=N'Kouritsu' where [Name] like N'%Kouritsu%'
Update tblProducts set Brand=N'Lutian' where [Name] like N'%Lutian%'
Update tblProducts set Brand=N'Promac' where [Name] like N'%Promac%'